name: CI

on:
  push:
    branches:
      - initial
  pull_request:
    branches:
      - initial

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: install node 16.14.2
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'

      - name: install dependencies
        run: npm install

      - name: unit test
        run: npm run test
